import {chromium,expect} from '@playwright/test';import {mkdirSync,writeFileSync} from 'node:fs';import {evidenceContext} from './evidence';
const b=await chromium.launch({channel:'chrome',headless:true,args:['--enable-webgl']});const p=await b.newPage({viewport:{width:1366,height:1000}}),rows=[],errors:string[]=[];p.on('pageerror',e=>errors.push(e.message));const dir='evidence/collection-refined';mkdirSync(dir,{recursive:true});
try{await p.goto((process.argv[2]??'http://127.0.0.1:5173')+'/?evidence');await p.waitForFunction(()=>!!window.__squishy&&(window.__squishy.snapshot() as {detailsReady:boolean}).detailsReady);
for(const [name,id] of [['Kitty Paw','paw'],['Sleepy Capybara','capybara']]){
 await p.getByRole('button',{name,exact:true}).click();await p.locator('#squishy').screenshot({path:`${dir}/${id}-rest.png`});const rest=await p.evaluate(()=>window.__squishy!.snapshot());await p.evaluate(()=>window.__squishy!.press());await p.waitForTimeout(2300);const held=await p.evaluate(()=>window.__squishy!.snapshot()) as {maxDisplacement:number;minVolumeRatio:number;safetyBackoffs:number};expect(held.maxDisplacement).toBeGreaterThan(.05);expect(held.minVolumeRatio).toBeGreaterThan(.17);expect(held.safetyBackoffs).toBe(0);await p.locator('#squishy').screenshot({path:`${dir}/${id}-held.png`});await p.evaluate(()=>window.__squishy!.release());await p.waitForTimeout(2000);const recovered=await p.evaluate(()=>window.__squishy!.snapshot()) as typeof held;expect(recovered.maxDisplacement).toBeLessThan(held.maxDisplacement);await p.getByRole('button',{name:'Reset shape',exact:true}).click();rows.push({name,rest,held,recovered});
 await p.setViewportSize({width:390,height:844});await p.locator('#squishy').scrollIntoViewIfNeeded();await p.locator('#squishy').screenshot({path:`${dir}/${id}-mobile.png`});expect(await p.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);await p.setViewportSize({width:1366,height:1000});
}
expect(errors).toEqual([]);writeFileSync(`${dir}/captures.json`,JSON.stringify({...evidenceContext(),conditions:'Desktop Chrome, normal wall time, 2.3 second standard hold and 2 second release. 390px mobile layout emulation, no AI inference.',rows,errors},null,2));console.log('Refined rest, held and mobile screenshots captured; release and reset verified.');
}finally{await b.close();}
