import { PRESETS } from './shared/spec';
import { COLLECTION,FACE_EXPRESSIONS } from './collection';
const thumbnail=(id:string)=>`<svg viewBox="0 0 80 52" aria-hidden="true" class="shape-thumbnail">${id==='berry'?'<path d="M19 17Q13 34 39 49Q64 34 61 17Q40 5 19 17" fill="#ee7890"/><path d="M22 17L32 8L40 15L48 7L58 16L42 22Z" fill="#67a67c"/><circle cx="31" cy="28" r="2.4" fill="#4c3c46"/><circle cx="47" cy="28" r="2.4" fill="#4c3c46"/><path d="M36 32Q39 37 43 32" fill="none" stroke="#4c3c46" stroke-width="1.8"/>':id==='mochi'?'<ellipse cx="40" cy="29" rx="28" ry="18" fill="#b8a5ef"/><ellipse cx="32" cy="21" rx="16" ry="7" fill="#d7c7ff" opacity=".5"/>':`<path d="M10 18L25 9L69 13L69 36L53 45L10 40Z" fill="${id==='jelly'?'#96d5e4':id==='butter'?'#e5c45e':'#e994b1'}"/><path d="M10 18L25 9L69 13L53 23Z" fill="${id==='jelly'?'#c9eef3':id==='butter'?'#f6df89':'#f8b8ce'}"/><path d="M53 23L69 13L69 36L53 45Z" fill="#ffffff" opacity=".16"/>${id==='jelly'?'<path d="M28 18L31 25L38 27L31 29L28 36L26 29L19 27L26 25Z" fill="#fff"/><circle cx="49" cy="17" r="2" fill="#fff"/>':`<text x="31" y="33" text-anchor="middle" fill="#fff9e9" font-size="${id==='butter'?8:5.8}" font-weight="800">${id==='butter'?'BUTTER':'STRAWBERRY'}</text>`}`}</svg>`;
const foodThumbnails:Record<string,string>={
  chocolate:'<path d="M9 19L22 9L69 15V36L57 45L9 38Z" fill="#75422e"/><path d="M12 18L24 11L66 16L55 25Z" fill="#aa7050"/><path d="M28 13L18 21M43 15L33 23M59 17L48 25M18 16L59 22" stroke="#643a2c" stroke-width="2"/><path d="M9 26L56 33L69 24" fill="none" stroke="#5d3427"/>',
  banana:'<path d="M12 16Q35 44 63 15L67 13Q64 43 41 45Q18 44 10 22Z" fill="#f4ce54"/><path d="M16 26Q37 48 60 27" fill="none" stroke="#d4aa36" stroke-width="2"/><path d="M10 16L14 13L19 19L14 23Z M61 16L65 10L70 11L67 17Z" fill="#84613d"/>',
  cat:'<path d="M15 24L16 8L30 18Q40 14 50 18L65 8L65 27Q72 48 41 49Q10 49 15 24" fill="#e9ab77"/><path d="M19 15L20 27L29 21M61 15L51 21L61 27" fill="#df8e91"/><circle cx="30" cy="30" r="2.5" fill="#423545"/><circle cx="50" cy="30" r="2.5" fill="#423545"/><path d="M37 35L43 35L40 38Z" fill="#af6b6b"/><path d="M27 36L17 34M53 36L63 34M36 20V24M44 20V24" stroke="#795b50" stroke-width="1.5"/>',
  cheese:'<path d="M10 25L42 9L69 24V43L10 43Z" fill="#e2a83b"/><path d="M10 25L42 9L69 24Z" fill="#ffe087"/><circle cx="24" cy="33" r="5" fill="#b7802c"/><circle cx="51" cy="35" r="6" fill="#b7802c"/><ellipse cx="41" cy="21" rx="5" ry="2.7" fill="#d79730"/>',
  peanut:'<path d="M10 26Q7 10 25 10Q34 10 40 17Q47 10 57 10Q74 10 72 27Q73 45 56 44Q46 44 40 37Q33 44 24 44Q7 43 10 26" fill="#d4a46e"/><path d="M12 20L28 39M15 13L37 35M28 12L38 24M12 32L28 14M20 42L35 23M45 23L56 12M44 35L65 13M54 41L70 23M46 17L69 35M44 28L58 43" stroke="#b78350" stroke-width="1.4"/>',
};
const collectionThumbnail=(id:string)=>foodThumbnails[id]?`<svg viewBox="0 0 80 52" aria-hidden="true" class="shape-thumbnail">${foodThumbnails[id]}</svg>`:thumbnail(id);
// English presentation copy stays separate from request and simulation logic.
const icon=(name:string)=>name==='reset'?'<path d="M4 10a8 8 0 1 1 2 7M4 4v6h6"/>':name==='rotate'?'<path d="M19 9c-1-3-13-3-14 0s12 6 14 2M16 7l3 2-3 3M5 15v2c0 4 14 4 14 0v-2"/>':'<path d="M7 4v7m5-9v9m5-7v8m-14 0 4 6c2 3 10 3 12-2l2-7M7 11c-3-3-5 0-3 3"/>';
const svg=(name:string)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icon(name)}</svg>`;
const smiley=(color:string)=>`<svg class="smile-doodle" viewBox="0 0 100 100" aria-hidden="true"><path d="M50 7C74 3 93 21 92 47C98 72 75 92 51 92C23 98 5 76 8 50C3 23 26 4 50 7Z" fill="${color}" stroke="#29263d" stroke-width="2.5"/><path d="M28 42Q34 32 40 42M60 42Q66 32 72 42" fill="none" stroke="#29263d" stroke-width="4" stroke-linecap="round"/><ellipse cx="24" cy="53" rx="7" ry="4" fill="#ff9caa"/><ellipse cx="76" cy="53" rx="7" ry="4" fill="#ff9caa"/><path d="M34 55Q50 79 66 55" fill="none" stroke="#29263d" stroke-width="4" stroke-linecap="round"/></svg>`;
const facePreview=(expression:string)=>`<svg viewBox="0 0 48 44" aria-hidden="true"><ellipse cx="24" cy="23" rx="20" ry="18" fill="#e5dafa"/><g stroke="#29263d" stroke-width="2" fill="none" stroke-linecap="round">${expression==='happy'?'<path d="M13 20Q16 15 19 20M29 20Q32 15 35 20M18 26Q24 39 30 26Z"/>':expression==='sleepy'?'<path d="M13 20Q16 24 19 20M29 20Q32 24 35 20M21 30H27"/>':expression==='wink'?'<circle cx="16" cy="20" r="2" fill="#29263d"/><path d="M29 20Q32 15 35 20M19 28Q24 34 29 28"/>':expression==='surprised'?'<circle cx="16" cy="20" r="2" fill="#29263d"/><circle cx="32" cy="20" r="2" fill="#29263d"/><ellipse cx="24" cy="30" rx="3" ry="4"/>':'<circle cx="16" cy="20" r="2" fill="#29263d"/><circle cx="32" cy="20" r="2" fill="#29263d"/><path d="M19 28Q24 34 29 28"/>'}</g><ellipse cx="11" cy="27" rx="3" ry="1.5" fill="#f3a6bc"/><ellipse cx="37" cy="27" rx="3" ry="1.5" fill="#f3a6bc"/></svg>`;
export const labMarkup=`
<div class="shell">
  <header class="topbar"><a class="brand" href="/" aria-label="Squishy Lab, home"><span class="brand-mark">${smiley('#c7b7fa')}</span>squishy<span>lab</span><span class="brand-dot" aria-hidden="true">✦</span></a><div class="top-actions"><a class="collection-link" href="#collection">The collection <span aria-hidden="true">↘</span></a><span class="mode-badge" id="mode-badge">Local demo · no AI</span><a class="repo-link" href="https://github.com/Daniele-Cangi/squishy-lab" target="_blank" rel="noopener noreferrer" aria-label="Open Squishy Lab on GitHub"><span class="repo-symbol" aria-hidden="true">{ }</span><span class="repo-label">GitHub</span><span aria-hidden="true">↗</span></a></div></header>
  <main>
    <div class="intro"><div class="intro-copy"><h1>Happiness<br/>is <span class="headline-highlight">squeezable.<svg viewBox="0 0 320 20" aria-hidden="true"><path d="M5 12Q140 1 313 10M23 17Q172 9 292 16" fill="none" stroke="currentColor" stroke-width="5" stroke-linecap="round"/></svg></span></h1><div class="vibe-sticker" aria-label="Visit counter"><span aria-hidden="true">☺</span><div>You’re squishy vibe <strong id="vibe-number">no. …</strong></div><span aria-hidden="true">✦</span></div></div><div class="intro-note" aria-hidden="true"><span class="hero-star">✳</span><div class="hero-smile">${smiley('#ffe277')}</div><span class="happy-sticker">100% good vibes <span>☺</span></span><span class="hero-caption">little shapes, big smiles.</span></div></div>
    <div class="workspace">
      <div class="object-column">
      <section class="play-area" aria-label="Playground">
        <div class="stage-top"><span class="stage-label"><span aria-hidden="true">✦</span> YOUR SQUISHY</span><div class="stage-top-right"><span class="state" id="state">Ready to squish</span><button id="sound-mode" type="button" class="sound-mode" aria-label="Sound texture" title="Switch between Gel and Crunchy" value="gel">Gel ↻</button><button id="sound" class="icon-button sound-toggle" aria-label="Disable squishy sound" aria-pressed="true" title="Sound on"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 9h4l5-4v14l-5-4H3zM16 8q5 4 0 8" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round"/><path class="sound-slash" d="m3 3 18 18" stroke="currentColor" stroke-width="2"/></svg></button></div></div>
        <div class="stage-doodles" aria-hidden="true"><span class="doodle-star">✧</span><span class="doodle-plus">+</span></div>
        <canvas id="squishy" tabindex="0" role="application" aria-label="3D squishy. Hold or drag to squeeze. On your keyboard, hold Space then release; Escape resets the shape." aria-describedby="gesture-help"></canvas>
        <div class="stage-bottom"><p id="gesture-help">Hold longer to sink deeper.<br/><span>Drag to move your squeeze.</span></p><div class="stage-actions"><button id="fullscreen-reset" class="icon-button" aria-label="Reset shape in fullscreen">${svg('reset')}</button><button id="rotate" class="icon-button" aria-label="Rotate view">${svg('rotate')}</button><button id="fullscreen" class="icon-button" aria-label="Enter fullscreen" aria-expanded="false" title="Enter fullscreen"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg></button></div></div>
        <div id="canvas-error" class="canvas-error" hidden>Your browser could not start WebGL 2. Try an up-to-date browser with graphics acceleration.</div>
      </section>
      <section class="under-stage" aria-label="Play controls and material"><div class="material-summary"><span id="color-chip"></span><div><strong id="material-name">Purple cloud</strong><p id="material-description">Super soft · slow return · matte</p></div></div><div class="play-actions"><button id="test-sound" class="text-button" type="button">Test sound</button><button id="squeeze" class="secondary">${svg('hand')}Hold to squish</button><button id="reset" class="text-button">${svg('reset')}Reset shape</button></div></section>
      <section id="comparison-row" class="comparison-row" aria-label="Material comparison" hidden><button id="compare" class="secondary">Compare before and after</button><div><strong id="comparison-phase">Same shape and color, same squeeze.</strong><p id="comparison-details"></p></div></section>
      </div>
      <div class="controls-column">
      <section class="collection" id="collection" aria-label="Shapes and finishes"><div class="collection-heading"><h2><span aria-hidden="true">🍡</span> Pick a shape</h2><span class="collection-count">10 little joys</span></div><div class="shape-list" role="group" aria-label="Collection">${COLLECTION.map((c,i)=>`<button class="shape-choice" data-shape="${c.id}" aria-label="${c.name}" title="${c.note}" aria-pressed="${c.id==='mochi'}"><small class="shape-number" aria-hidden="true">${String(i+1).padStart(2,'0')}</small>${collectionThumbnail(c.id)}<span>${c.name}</span></button>`).join('')}</div><div class="finish-row"><div class="finish-options" role="group" aria-label="Surface finish"><button data-effect="foam" aria-pressed="true">Soft touch</button><button data-effect="glitter" aria-pressed="false">✦ Glitter</button><button data-effect="clear" aria-pressed="false">Clear ✦</button></div><label class="face-option"><input type="checkbox" id="face"/>Show face <span aria-hidden="true">☺</span></label></div><div class="expression-row"><span>Pick a mood</span><div class="expression-list" role="group" aria-label="Face expression">${FACE_EXPRESSIONS.map(expression=>`<button data-expression="${expression}" aria-label="${expression[0].toUpperCase()+expression.slice(1)} face" aria-pressed="${expression==='smile'}">${facePreview(expression)}<span>${expression[0].toUpperCase()+expression.slice(1)}</span></button>`).join('')}</div></div></section>
      <section class="personalization" aria-label="Personalize your squishy"><h2>Make it yours ✨</h2><label for="custom-text">A little message</label><input id="custom-text" maxlength="40" placeholder="Hello, sunshine!" autocomplete="off"/><p>Your message replaces the face. Clear it to bring the face back.</p><label for="text-color">Text color</label><input id="text-color" type="color" value="#47334e"/><div class="cute-fonts" role="group" aria-label="Lettering font"><button data-font="Chewy" style="font-family:'Chewy'" aria-pressed="true">Chewy</button><button data-font="Baloo 2" style="font-family:'Baloo 2'" aria-pressed="false">Baloo 2</button><button data-font="Pacifico" style="font-family:'Pacifico'" aria-pressed="false">Pacifico</button><button data-font="Short Stack" style="font-family:'Short Stack'" aria-pressed="false">Short Stack</button></div><button id="download-png" class="secondary">Download PNG ↓</button><p id="download-status" role="status"></p></section>
      </div>
      <aside class="composer">
        <div class="composer-topline"><span>LET’S MAKE IT SQUISHY</span><span aria-hidden="true">✦</span></div>
        <div class="composer-heading"><span class="step">01</span><h2>Give it an idea <span aria-hidden="true">💭</span></h2></div>
        <form id="prompt-form">
          <label for="prompt">Color, softness, recovery…</label>
          <textarea id="prompt" maxlength="500" rows="4" placeholder="A purple mochi, very soft, with a slow return."></textarea>
          <div class="request-kind" role="group" aria-label="Request type"><button type="button" id="modify-mode" class="selected" aria-pressed="true">Edit this one</button><button type="button" id="create-mode" aria-pressed="false">Create a new one</button></div>
          <div id="turnstile"></div>
          <button class="primary" id="generate" type="submit"><span id="generate-label">Apply description</span><span class="button-spark" aria-hidden="true">✦</span></button>
          <p class="privacy" id="privacy">Local demo interpreter: recognizes a few words without AI or sending your description.</p>
          <p id="status" class="status" role="status" aria-live="polite">Try “same, but a little firmer”.</p>
        </form>
        <div class="divider"></div>
        <div class="composer-heading"><span class="step">02</span><h2>Or start with a favorite</h2></div>
        <p class="preset-note">Three ready-to-squish materials.</p>
        <div class="presets">${PRESETS.map((p,i)=>`<button class="preset ${i===0?'active':''}" data-preset="${i}" aria-pressed="${i===0}"><span class="swatch" style="--swatch:${p.spec.color}"></span><span><strong>${p.name}</strong><small>${p.description}</small></span><span class="preset-check" aria-hidden="true">✓</span></button>`).join('')}</div>
        <div class="little-reminder"><span aria-hidden="true">☁️</span><p>Take your time.<br/><strong>Good things bounce back.</strong></p><span class="reminder-spark" aria-hidden="true">✧</span></div>
      </aside>
    </div>
  </main>
  <footer><span class="footer-note"><span aria-hidden="true">☺</span> Little shapes. Big feelings.</span><span id="model-credit" hidden>Built with Llama · Cloudflare Workers AI</span><button id="forget">Clear saved squishy</button><p class="dedication">Made for August, certified squishy expert. ☺</p></footer>
</div>`;

